[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
derive_more = { version = "1.0.0", default-features = false, features = [
    "from",
] }
displaydoc = "0.2.5"
libc = "0.2.167"
serde = { version = "1.0.215", features = ["derive"] }
thiserror = "2.0.7"
vmm-sys-util = "0.12.1"

[dev-dependencies]
serde_json = "1.0.133"


[lints]
workspace = true
